<?php
// Powerstone Affiliate Me, Version 2.1.4 https://www.powerstonegh.com.
if(empty($link)){header('Location: ./admin.php'); exit;}
$tid = $_GET["id"];
if(!empty($_POST) && strtolower($_SERVER['HTTP_HOST'])==strtolower(parse_url($_SERVER['HTTP_REFERER'], PHP_URL_HOST))){
$nam = mysqli_real_escape_string($link, $_POST['name']);
$tp = mysqli_real_escape_string($link, $_POST['type']);
$message = mysqli_real_escape_string($link, $_POST['message']);
$sql9z = "UPDATE etemplates SET NAME='".$nam."', TYPE='".$tp."', MESSAGE='".$message."' WHERE ID = '" . $tid . "' ";
$result = mysqli_query($link, $sql9z);
$sucm = "Email Template Successfully Saved";
}
$sqlz = "SELECT * FROM etemplates WHERE ID = '" . $tid . "' ";
$result = mysqli_query($link, $sqlz);
$row = mysqli_fetch_array($result);
                    $name = $row['NAME'] ;
                    $type = $row['TYPE'] ;
                    $mess = $row['MESSAGE'] ;

if($row['TYPE'] == "signup"){$typ = "Sign Up";} else if($row['TYPE'] == "recovery"){$typ = "Password Recovery";} else if($row['TYPE'] == "reply"){$typ = "Ticket Reply";} else if($row['TYPE'] == "sales"){$typ = "Sales Alert";} else if($row['TYPE'] == "payout"){$typ = "Affiliate Payout Alert";} else if($row['TYPE'] == "paycancel"){$typ = "Payout Cancel Alert";}
?><!doctype html><html><head><meta charset="utf-8"><title>Create Email Templates | Affiliate Me - <?php echo $version; ?></title><meta name="robots" content="noindex, nofollow"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link href="editemp.css" rel="stylesheet"><script src="jquery-1.12.4.min.js"></script></head><body><div id="container"><div id="Html10"><?php
if($sucm !='') {
echo "<div class=\"alert\"> <span class=\"closebtn\" onclick=\"this.parentElement.style.display='none';\">&times;</span> <div style=\"font-size:12px;\"><center><i class=\"fa fa-check-circle-o\">&nbsp;</i><strong>" . $sucm . "</strong></center></div></div>";
}
if($err !='') {
echo "<div class=\"alert2\"> <span class=\"closebtn\" onclick=\"this.parentElement.style.display='none';\">&times;</span> <div style=\"font-size:12px;\"><center><i class=\"fa fa-info-circle\">&nbsp;</i><strong>" . $err . "</strong></center></div></div>";
}
?></div><div id="wb_Form1"><form name="Form1" method="post" action="admin.php?show=editemp&id=<?php echo $tid; ?>" enctype="multipart/form-data" id="Form1" onsubmit="rev();document.getElementById('Form1').submit();return false;"><input type="text" id="Editbox1" name="name" value="<?php echo $name; ?>" readonly autocomplete="off" spellcheck="false" required placeholder="<?php echo $lang['pgname']; ?>"><select name="type" size="1" id="Combobox1"><option value="<?php echo $type; ?>"><?php echo $typ; ?></option></select><div id="Html1"><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;"><strong><?php echo $lang["var"]; ?>:</strong></span><br><?php
if($type == "signup"){echo '<div><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">'.$lang['sitename'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ sitename }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user_name'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ fullname }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ username }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['userpass'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ password }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['sysmail'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ semail }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['logo'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">'.$prot.$domain.'/'.$logo.'</span></div>';} else
if($type == "recovery"){echo '<div><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">'.$lang['sitename'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ sitename }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user_name'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ fullname }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ username }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['recover'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ recover }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['sysmail'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ semail }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['logo'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">'.$prot.$domain.'/'.$logo.'</span></div>';} else
if($type == "reply"){echo '<div><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">'.$lang['sitename'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ sitename }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user_name'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ fullname }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['tisub'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ subject }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['tickmes'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ message }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['tid'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ ticket }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['logo'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">'.$prot.$domain.'/'.$logo.'</span></div>';} else
if($type == "sales"){echo '<div><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">'.$lang['sitename'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ sitename }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user_name'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ fullname }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['cradd'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ credit }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['logo'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">'.$prot.$domain.'/'.$logo.'</span></div>';} else
if($type == "payout"){echo '<div><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">'.$lang['sitename'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ sitename }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user_name'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ fullname }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['transid'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ transaction }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['logo'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">'.$prot.$domain.'/'.$logo.'</span></div>';} else
if($type == "paycancel"){echo '<div><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">'.$lang['sitename'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ sitename }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['user_name'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ fullname }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['transid'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">{{ transaction }}</span><span style="color:#D3D3D3;font-family:Tahoma;font-size:13px;">, '.$lang['logo'].': </span><span style="color:#00CED1;font-family:Tahoma;font-size:13px;">'.$prot.$domain.'/'.$logo.'</span></div>';}
?></div><div id="Html2"><div style="font-size:13px;" class="page-wrapper box-content"><textarea class="content" name="message"><?php echo $mess; ?></textarea></div><script>
$(document).ready(function(){$('.content').richText();});</script></div><div id="paybut"><button id="save" type="submit show" class="butt"><i class="fa fa-save">&nbsp;</i>&nbsp;<?php echo $lang['save_changes']; ?></button><button id="saving" class="button2 hide" disabled><div class="fa fa-spinner fa-pulse"></div>&nbsp;&nbsp;<?php echo $lang['saving_changes']; ?></button><script>
function rev(){var element=document.getElementById("save");element.classList.remove("show");element.classList.add("hide");var element=document.getElementById("saving");element.classList.remove("hide");element.classList.add("show");}</script></div></form></div></div></body></html>